[[redirects]]
  from = "https://padp-staging.netlify.app/admin/*"
  to = "https://padp.staging.performant.studio/admin/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://padp-staging.netlify.app/admin/*"
  to = "http://padp.staging.performant.studio/admin/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://padp.staging.performant.studio/en/*"
  to = "https://padp-staging.netlify.app/en/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://padp.staging.performant.studio/en/*"
  to = "http://padp-staging.netlify.app/en/:splat"
  status = 301
  force = true
